version: '3.8'

services:
  db-pedidos-servicio:
    image: mysql:8.0
    container_name: mysql_pedidos
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: db_amazorg_pedidos
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3312:3306"
    networks:
      - red_interna_pedidos
    volumes:
      - persistencia_db_pedidos:/var/lib/mysql

  workspace-java-pedidos:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_programacion_pedidos
    ports:
      - "8086:8086"
    depends_on:
      - db-pedidos-servicio
    networks:
      - red_interna_pedidos
    command: tail -f /dev/null
    volumes:
      - ./codigo-fuente:/app
    working_dir: /app

networks:
  red_interna_pedidos:

volumes:
  persistencia_db_pedidos: