# Nombre de la aplicación en el ecosistema Spring Cloud
spring.application.name=pedidos-service

# Puerto asignado a tu microservicio de Pedidos
server.port=8086

# Configuración de la base de datos MySQL relacional
spring.datasource.url=jdbc:mysql://mysql_pedidos:3306/db_amazorg_pedidos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate y persistencia
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# FASE 3: URLs dinámicas para Clientes Feign (Escenario B: AWS EC2)
# Permite resolución por variable de entorno inyectada desde Docker o fallback a localhost
auth.service.url=[http://13.216.24.99:8081](http://13.216.24.99:8081)
promociones.service.url=http://[IP_ELASTICA_JOSEFA]:80851

# FASE 4: Directivas obligatorias de Tolerancia a Fallos y Resiliencia
# Tiempo máximo en milisegundos para establecer la conexión TCP con el servicio destino
spring.cloud.openfeign.client.config.default.connectTimeout=3000

# Tiempo máximo en milisegundos para esperar la respuesta del servicio tras conectar
spring.cloud.openfeign.client.config.default.readTimeout=5000